apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: parksmap-web-mitzicom
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      app: parksmap-web
    name: parksmap-web
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: parksmap-web
      deploymentconfig: parksmap-web
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: parksmap-web
          deploymentconfig: parksmap-web
      spec:
        containers:
        - image: docker-registry.default.svc:5000/mitzicom-dev/parksmap-web@sha256:bbb8750617ce0281a2c2bd4e789aac68369da1228bc59a795fc3126cd75b1469
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /ws/backends/list/
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 120
          name: parksmap-web
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ws/healthz/
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 120
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - imageChangeParams:
        containerNames:
        - parksmap-web
        from:
          kind: ImageStreamTag
          name: parksmap-web:latest
          namespace: mitzicom-dev
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: parksmap-web
    name: parksmap-web
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: parksmap-web
      deploymentconfig: parksmap-web
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    creationTimestamp: null
    labels:
      app: parksmap-web
    name: parksmap-web
  spec:
    host: parksmap-web-mitzicom-dev.apps.46.4.112.21.xip.io
    port:
      targetPort: 8080
    to:
      kind: Service
      name: parksmap-web
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - lastTransitionTime: 2018-02-13T10:30:16Z
        status: "True"
        type: Admitted
      host: parksmap-web-mitzicom-dev.apps.46.4.112.21.xip.io
      routerName: router
      wildcardPolicy: None
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      app: parksmap-web
      build: parksmap-web
    name: parksmap-web
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: parksmap-web:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      binary: {}
      type: Binary
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: redhat-openjdk18-openshift:1.2
          namespace: openshift
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: _VOTvyaUuh90kwpEKyHb
      type: GitHub
    - generic:
        secret: tJKnUhrF3ynT1UxLK_Gk
      type: Generic
  status:
    lastVersion: 0
